services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /app
    volumes:
      - ./symfony:/app:delegate
    ports:
      - "8000:8000"
    environment:
      SYMFONY_ENV: prod
      MAILER_DSN: smtp://mailhog:1025
    depends_on:
      - db
      - mailhog
    command: sh -c "sleep 5 && composer install && composer run migrate && composer run generate:keys && php -S 0.0.0.0:8000 -t public"

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: symfony_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  db_data:
